" Enable pathogen plugin manager 
runtime bundle/vim-pathogen/autoload/pathogen.vim
execute pathogen#infect()

" Gutter plugin update time (100ms is recommended)
set updatetime=100

" Add line numbers
set number

" Enable nord theme if exists
try
    set t_Co=256
    colorscheme nord
catch /^Vim\%((\a\+)\)\=:E185/
    " No color scheme selected
endtry
 
" Set tabing to 2 spaces
filetype plugin indent on
set expandtab
set tabstop=2
set softtabstop=2
set shiftwidth=2

" Disable annoying noises
set visualbell
